server:
  forward-headers-strategy: native
  shutdown: graceful
  port: 8080
spring:
  mvc:
    async:
      request-timeout: 600000
  application:
    name: exam2025
  config:
    import: 'optional:configserver:'
  cloud:
    discovery:
      enabled: false
  resources.add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/exam2025?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true&serverTimezone=UTC
    username: root
    password: 11223344
management:
  endpoint:
    health:
      logging:
        slow-indicator-threshold: 100ms
springdoc:
  swagger-ui:
    enabled: true
    filter: true
    tryItOutEnabled: true
exam:
  test: 1234